spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      function:
        definition: userCreatedConsumer;userCreatedProducer
      bindings:
        userCreatedConsumer-in-0:
          destination: user_topic
          group: group-in-0
          content-type: application/*+avro
          consumer:
            concurrency: 1
            max-attempts: 5
            use-native-decoding: true
        userCreatedProducer-out-0:
          destination: user_topic
          content-type: application/*+avro
          producer:
            use-native-encoding: true
      schema-registry-client:
        endpoint: http://localhost:8081
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: false
          auto-add-partitions: false
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: ${spring.cloud.stream.schema-registry-client.endpoint}
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: ${spring.cloud.stream.schema-registry-client.endpoint}
            specific.avro.reader: true
        bindings:
          userCreatedConsumer-in-0:
            consumer:
              auto-commit-offset: false # true enabled autoCommit
